config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  resources :surveys do 
    resources :questions 
    get 'report', on: :member
  end
  resources :answers
  root "surveys#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :surveys, dependent: :destroy
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :survey
  has_many :answers, dependent: :destroy
  validates :title, presence: true
  
   def next
    Question.where("id > ?", id).first
   end

   def previous
    Question.where("id < ?", id).last
   end
end

app/models/survey.rb
class Survey < ApplicationRecord
  belongs_to :admin
  has_many :questions, dependent: :destroy

  validates :title, presence: true
  validates :description, presence: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    @answer = Answer.new(answer_params)
    last_question = Question.where(survey_id:@answer.question.survey.id).order(:id).last
    if @answer.save
      if @answer.question_id != last_question.id
        redirect_to survey_path(@answer.question.survey, question_id:@answer.question_id + 1)
        flash.notice = 'Answer succesfully recorded'
      else
        redirect_to root_path
        flash.notice = 'Answer succesfully recorded'
      end
    else
      render :new, status: :unprocessable_entity
      flash.alert = 'Answer could not be recorded'
    end
  end

  private
  def answer_params
    params.require(:answer).permit(:question_id,:choice_1, :choice_2, :choice_3, :choice_4, :choice_5, :choice_6, :open_ended_answer, :multiple_answer_choice)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_question, except: %i[new create destroy]

  def new
    @survey = Survey.find(params[:survey_id])
    @question = @survey.questions.new  
  end

  def create
    @survey = Survey.find(params[:survey_id])
    @question = @survey.questions.new(question_params)

    if @question.save
      redirect_to edit_survey_path(@survey)
      flash.notice = 'Added question'
    else
      render :new, status: :unprocessable_entity
      flash.alert = 'Failed to add question'
    end
  end

  def update 
    if @question.update(question_params)
      redirect_to edit_survey_path(@question.survey)
      flash.notice = 'Updated question'
    else
      render :edit, status: :unprocessable_entity
      flash.alert = 'Failed to update question'
    end
  end
  
  def destroy
    @question = Question.find(params[:question_id])  

    @question.destroy
    redirect_to edit_survey_path(@question.survey), status: :see_other
  end

  private
  def set_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :question_type, :choice_1, :choice_2, :choice_3, :choice_4, :choice_5, :choice_6, :open_ended_answer, :multiple_answer_choice)
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :authenticate_admin!, except: %i[index show]
  before_action :set_survey, except: %i[index new create]

  def index
    @surveys = Survey.all
  end
  
  def show
    if params[:question_id] == nil and @survey.questions.first != nil
      @question = @survey.questions.first
      @answer = @question.answers.new()
    elsif params[:question_id] != nil and @survey.questions.first != nil
      @question = Question.find(params[:question_id])
      @answer = @question.answers.new()
    else
      @question = nil
    end
  end

  def new
    @survey = Survey.new
  end

  def create 
    admin = current_admin
    @survey = admin.surveys.new(survey_params)

    if @survey.save
      redirect_to edit_survey_path(@survey)
      flash.notice = 'Created survey'
    else
      render :new, status: :unprocessable_entity
      flash.alert = 'Failed to create survey'
    end
  end

  def update
    if @survey.update(survey_params)
      redirect_to edit_survey_path(@survey)
      flash.notice = 'Updated survey'
    else
      render :edit, status: :unprocessable_entity
      flash.alert = 'Failed to update survey' 
    end
  end

  def destroy
    @survey.destroy
    redirect_to root_path, status: :see_other
  end

  private
  def set_survey
    @survey = Survey.find(params[:id])
  end

  def survey_params
    params.require(:survey).permit(:title, :description)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title SurveyApp
    meta content="width=device-width,initial-scale=1" name="viewport" /
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  body
    nav.navbar.navbar-expand-lg.navbar-dark.bg-dark 
      a.navbar-brand href="#" Survey-app
      button.navbar-toggler aria-controls="navbarText" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarText" data-toggle="collapse" type="button" 
        span.navbar-toggler-icon
      #navbarText.collapse.navbar-collapse
        ul.navbar-nav.mr-auto
          li.nav-item.active
            a.nav-link href=root_path 
              | Home
              span.sr-only (current)         
    - if flash[:notice]
      .container.d-flex.align-items-center.justify-content-center
        .alert.alert-primary
          = flash[:notice]
    - if flash[:alert]
      .container.d-flex.align-items-center.justify-content-center
        .alert.alert-danger
          = flash[:alert]
    = yield

app/views/questions/_form.html.slim
- if params[:question_type] == nil
  = form_with method: :get do |form|
    div class='mb-3'
      = form.label :question_type, class:'form-label'
      br/
      = form.select :question_type, [['multiple choice','multiple_choice'], ['open-ended', 'open_ended'], ['multiple-answer','multiple_answer']],class:'form-select'
    div class='mb-3'
      = form.submit 'Submit', class:'btn btn-success'

-elsif params[:question_type] == 'multiple_choice'
    = form_with model: [survey, question] do |form|
      div class='mb-3'
        = form.hidden_field :question_type ,value:params[:question_type]
      div class='mb-3'
        = form.label :title, class:'form-label'
        = form.text_area :title, class:'form-control'
      div class='mb-3'
        = form.label :choice_1, class:'form-label'
        = form.text_field :choice_1, class:'form-control'
      div class='mb-3'
        = form.label :choice_2, class:'form-label'
        = form.text_field :choice_2, class:'form-control'
      div class='mb-3'
        = form.label :choice_3, class:'form-label'
        = form.text_field :choice_3, class:'form-control'
      div class='mb-3'
        = form.label :choice_4, class:'form-label'
        = form.text_field :choice_4, class:'form-control'
      div class='mb-3'
        = form.label :choice_5, class:'form-label'
        = form.text_field :choice_5, class:'form-control'
      div class='mb-3'
        = form.label :choice_6, class:'form-label'
        = form.text_field :choice_6, class:'form-control'
      div class='mb-3'
        = form.submit 'Submit', class:'btn btn-success' 

-elsif params[:question_type] == 'open_ended'
    = form_with model: [survey, question] do |form|
      div class='mb-3'
        = form.hidden_field :question_type ,value:params[:question_type]
      div class='mb-3'
        = form.label :title, class:'form-label'
        = form.text_area :title, class:'form-control'
      div class='mb-3'
        = form.submit 'Submit', class:'btn btn-success'

-elsif params[:question_type] == 'multiple_answer'
    = form_with model: [survey, question] do |form|
      div class='mb-3'
        = form.hidden_field :question_type ,value:params[:question_type]
      div class='mb-3'
        = form.label :title, class:'form-label'
        = form.text_area :title, class:'form-control'
      div class='mb-3'
        = form.label :choice_1, class:'form-label'
        = form.text_field :choice_1, class:'form-control'
      div class='mb-3'
        = form.label :choice_2, class:'form-label'
        = form.text_field :choice_2, class:'form-control'
      div class='mb-3'
        = form.label :choice_3, class:'form-label'
        = form.text_field :choice_3, class:'form-control'
      div class='mb-3'
        = form.label :choice_4, class:'form-label'
        = form.text_field :choice_4, class:'form-control'
      div class='mb-3'
        = form.label :choice_5, class:'form-label'
        = form.text_field :choice_5, class:'form-control'
      div class='mb-3'
        = form.label :choice_6, class:'form-label'
        = form.text_field :choice_6, class:'form-control'
      div class='mb-3'
        = form.submit 'Submit', class:'btn btn-success'

app/views/questions/edit.html.slim
div class='container d-flex align-items-center justify-content-center'
  -if @question.question_type == 'multiple_choice'
      = form_with model: [@question.survey, @question]do |form|
        div class='mb-3'
          = form.hidden_field :question_type,value: 'multiple_choice'
        div class='mb-3'
          = form.label :title, class:'form-label'
          = form.text_area :title, class:'form-control'
        div class='mb-3'
          = form.label :choice_1, class:'form-label'
          = form.text_field :choice_1, class:'form-control'
        div class='mb-3'
          = form.label :choice_2, class:'form-label'
          = form.text_field :choice_2, class:'form-control'
        div class='mb-3'
          = form.label :choice_3, class:'form-label'
          = form.text_field :choice_3, class:'form-control'
        div class='mb-3'
          = form.label :choice_4, class:'form-label'
          = form.text_field :choice_4, class:'form-control'
        div class='mb-3'
          = form.label :choice_5, class:'form-label'
          = form.text_field :choice_5, class:'form-control'
        div class='mb-3'
          = form.label :choice_6, class:'form-label'
          = form.text_field :choice_6, class:'form-control'
        div class='mb-3'
          = form.submit 'Submit', class:'btn btn-success' 

  -elsif @question.question_type == 'open_ended'
      = form_with model: [@question.survey, @question] do |form|
        div class='mb-3'
          = form.hidden_field :question_type,value:'open_ended'
        div class='mb-3'
          = form.label :title, class:'form-label'
          = form.text_area :title, class:'form-control'
        div class='mb-3'
          = form.submit 'Submit', class:'btn btn-success'

  -elsif @question.question_type == 'multiple_answer'
      = form_with model: [@question.survey, @question] do |form|
        div class='mb-3'
          = form.hidden_field :question_type,value: 'multiple_answer'
        div class='mb-3'
          = form.label :title, class:'form-label'
          = form.text_area :title, class:'form-control'
        div class='mb-3'
          = form.label :choice_1, class:'form-label'
          = form.text_field :choice_1, class:'form-control'
        div class='mb-3'
          = form.label :choice_2, class:'form-label'
          = form.text_field :choice_2, class:'form-control'
        div class='mb-3'
          = form.label :choice_3, class:'form-label'
          = form.text_field :choice_3, class:'form-control'
        div class='mb-3'
          = form.label :choice_4, class:'form-label'
          = form.text_field :choice_4, class:'form-control'
        div class='mb-3'
          = form.label :choice_5, class:'form-label'
          = form.text_field :choice_5, class:'form-control'
        div class='mb-3'
          = form.label :choice_6, class:'form-label'
          = form.text_field :choice_6, class:'form-control'
        div class='mb-3'
          = form.submit 'Submit', class:'btn btn-success'

app/views/questions/new.html.slim
div class='container d-flex align-items-center justify-content-center'
  h1 New question 

div class='container d-flex align-items-center justify-content-center'
  = render 'form', {survey:@survey, question:@question}

app/views/surveys/_form.html.slim
= form_with model:survey do |form|
  div class='mb-3'
    = form.label :title, class:'form-label'
    br
    = form.text_field :title, class:'form-control'
    ul
    - survey.errors.full_messages_for(:title).each do |message|
      li
        = message
  div class='mb-3'
    = form.label :description, class:'form-label'
    br
    = form.text_area :description, class:'form-control'
    - survey.errors.full_messages_for(:description).each do |message|
      li
        = message
  div class='mb-3'
    = form.submit 'Submit', class:'btn btn-md btn-success'

app/views/surveys/edit.html.slim
div class='container d-flex align-items-center justify-content-center'
  h1 Edit Survey

div class='container d-flex align-items-center justify-content-center'
  = render 'form', survey:@survey

div class='container d-flex align-items-center justify-content-center'
  h1 Questions

div class='container d-flex align-items-center justify-content-center'
  table class='table table-hover table-bordered'   
    thead
      tr 
        th Title
        th Edit
        th Delete
    tbody
    - @survey.questions.each do |question|
      tr 
        td class='question-title'
          = question.title
        td 
          = link_to 'Edit question', edit_survey_question_path(@survey, question),class:'btn btn-primary btn-md'
        td
          = link_to 'Delete question', survey_question_path(@survey, question, question_id:question.id), data: {turbo_method: :delete, turbo_confirm:'Are you sure?'}, class:'btn btn-danger btn-md'
div class='container d-flex align-items-center justify-content-center'
  = link_to 'Add questions', new_survey_question_path(@survey), class:'btn btn-success btn-lg'

app/views/surveys/index.html.slim
div class='container d-flex align-items-center justify-content-center'
  h1 Surveys
div class='container d-flex align-items-center justify-content-center'
  - if !admin_signed_in?
    = link_to 'sign-up', 'admins/sign_up',class:'btn btn-primary'
    = link_to 'sign-in', 'admins/sign_in',class:'btn btn-success'
  - if admin_signed_in?
    = link_to "Sign Out", destroy_admin_session_path, data:{turbo_method: :delete}, class:'btn btn-danger'


br
div class='container d-flex align-items-center justify-content-center'
  - if !@surveys.empty?
    table class='table table-hover table-bordered'
      thead
        tr 
          th Title
          th Admin
          - if admin_signed_in?
            th Edit
            th Delete
            th Reports
      - @surveys.each do |survey|
        tr
          td
            = link_to survey.title, survey
          td
            = survey.admin.email
          - if admin_signed_in?
            td
              - if current_admin == survey.admin
                  = link_to 'Edit Survey', edit_survey_path(survey), class:'btn btn-primary'
            td
              - if current_admin == survey.admin
                  = link_to 'Delete Survey', survey_path(survey, survey_id:survey.id), data:{ turbo_method: :delete, tirbo_confirm:'Are you sure'}, class:'btn btn-danger'
            td
              - if current_admin == survey.admin
                  = link_to 'Get a report', survey_path(survey) + '/report', class:'btn btn-info'
  -else
    div class='container d-flex align-items-center justify-content-center'
      div class='alert alert-primary'
        h4 class='alert heading' There are no surveys
        - if !admin_signed_in?
          p class='mb-3' Please come back later when there are more surveys
        -else
          p class='mb-3'Please come back later when there are more surveys, or add a survey

div class='container d-flex align-items-center justify-content-center'
  - if admin_signed_in?
    = link_to 'Add a new Survey', new_survey_path, class:'btn btn-success'

app/views/surveys/new.html.slim
div class='container d-flex align-items-center justify-content-center'
  h1 Create a new Survey
div class='container d-flex align-items-center justify-content-center'
  = render 'form', survey:@survey

app/views/surveys/report.html.slim
- if current_admin == @survey.admin

  div class='container d-flex align-items-center justify-content-center'
    h1 Survey:#{@survey.title}


  - @survey.questions.each do |question|
    div class='container d-flex align-items-center justify-content-center'
      h2 Question:#{question.title}
    div class='container d-flex align-items-center justify-content-center'
      - if question.question_type == 'multiple_choice'
          ul
            - if question.choice_1 != ''    
                li class='list-group-item'
                  = question.choice_1 + ': ' + question.answers.where(multiple_answer_choice:question.choice_1).count().to_s + ' responses'
            - if question.choice_2 != ''
                li class='list-group-item'
                  = question.choice_2 + ': ' + question.answers.where(multiple_answer_choice:question.choice_2).count().to_s + ' responses'
            - if question.choice_3 != ''
                li class='list-group-item'
                  = question.choice_3 + ': ' + question.answers.where(multiple_answer_choice:question.choice_3).count().to_s + ' responses'
            - if question.choice_4 != ''
                li class='list-group-item'
                  = question.choice_4 + ': ' + question.answers.where(multiple_answer_choice:question.choice_4).count().to_s + ' responses'
            - if question.choice_5 != ''    
                li class='list-group-item'
                  = question.choice_5 + ': ' + question.answers.where(multiple_answer_choice:question.choice_5).count().to_s + ' responses'
            - if question.choice_6 != ''    
                li class='list-group-item'
                  = question.choice_6 + ': ' + question.answers.where(multiple_answer_choice:question.choice_6).count().to_s + ' responses'
      - elsif question.question_type == 'multiple_answer'
          ul
            - if question.choice_1 != ''    
                li class='list-group-item'
                  = question.choice_1 + ': ' + question.answers.where(choice_1:true).count().to_s + ' responses'
            - if question.choice_2 != ''
                li class='list-group-item'
                  = question.choice_2 + ': ' + question.answers.where(choice_2:true).count().to_s + ' responses'
            - if question.choice_3 != ''
                li class='list-group-item'
                  = question.choice_3 + ': ' + question.answers.where(choice_3:true).count().to_s + ' responses'
            - if question.choice_4 != ''
                li class='list-group-item'
                  = question.choice_4 + ': ' + question.answers.where(choice_4:true).count().to_s + ' responses'
            - if question.choice_5 != ''    
                li class='list-group-item'
                  = question.choice_5 + ': ' + question.answers.where(choice_5:true).count().to_s + ' responses'
            - if question.choice_6 != ''    
                li class='list-group-item'
                  = question.choice_6 + ': ' + question.answers.where(choice_6:true).count().to_s + ' responses' 
      - elsif question.question_type == 'open_ended' 
        ul
          -question.answers.each do |answer|
            li class='list-group-item'
              p #{answer.open_ended_answer}        
-else
    div class='container d-flex align-items-center justify-content-center'
      div class='alert alert-danger'
        h4 class='alert heading' You don't have access to this report



                  
            

app/views/surveys/show.html.slim
div class='container d-flex align-items-center justify-content-center'
  h1 #{@survey.title}
- if @question != nil

  div class='container d-flex align-items-center justify-content-center'
    h2 Question: #{@question.title}

  div class='container d-flex align-items-center justify-content-center'  
    -if @question.question_type == 'multiple_choice'
        = form_with model: @answer do |form|
          div class='mb-3'
            = form.hidden_field :question_id, value:@question.id
          - if @answer.question.choice_1 != ''
            div class='form-check mb-3'
              = form.radio_button :multiple_answer_choice, @answer.question.choice_1, class:'form-check-input'
              = form.label @answer.question.choice_1, class:'form-check-label'
          - if @answer.question.choice_2 != ''
            div class='form-check mb-3'
              = form.radio_button :multiple_answer_choice, @answer.question.choice_2, class:'form-check-input'
              = form.label @answer.question.choice_2, class:'form-check-label'
          - if @answer.question.choice_3 != ''
            div class='form-check mb-3'
              = form.radio_button :multiple_answer_choice, @answer.question.choice_3, class:'form-check-input'
              = form.label @answer.question.choice_3, class:'form-check-label'
          - if @answer.question.choice_4 != ''
            div class='form-check mb-3'
              = form.radio_button :multiple_answer_choice, @answer.question.choice_4, class:'form-check-input'
              = form.label @answer.question.choice_4, class:'form-check-label'
          - if @answer.question.choice_5 != ''
            div class='form-check mb-3'
              = form.radio_button :multiple_answer_choice, @answer.question.choice_5, class:'form-check-input'
              = form.label @answer.question.choice_5, class:'form-check-label'
          - if @answer.question.choice_6 != ''
            div class='form-check mb-3'
              = form.radio_button :multiple_answer_choice, @answer.question.choice_6, class:'form-check-input'
              = form.label @answer.question.choice_6, class:'form-check-label'
          
          nav
            ul class='pagination'
              - if @question.next != nil
                li.page-item
                  = form.submit 'Next', class:'page-link'
              - elsif @question.next == nil
                  li.page-item
                        = form.submit 'Submit', class:'page-link' 

    -elsif @question.question_type == 'open_ended'
        = form_with model: @answer  do |form|
          div class='mb-3'
            = form.hidden_field :question_id, value:@question.id
          div class='mb-3'
            = form.label @answer.question.title, class:'form-label'
            = form.text_area :open_ended_answer, class:'form-control'
          
          nav
            ul class='pagination'
              - if @question.next != nil
                li.page-item
                  = form.submit 'Next', class:'page-link'
              - elsif @question.next == nil
                  li.page-item
                        = form.submit 'Submit', class:'page-link' 
          
    -elsif @question.question_type == 'multiple_answer'
        = form_with model: @answer  do |form|
          div class='mb-3'
            = form.hidden_field :question_id, value:@question.id
          - if @answer.question.choice_1 != ''
            div class='form-check mb-3'
              = form.check_box :choice_1, class:'form-check-input'
              = form.label @answer.question.choice_1, class:'form-check-label'
          - if @answer.question.choice_2 != ''
            div class='form-check mb-3'
              = form.check_box :choice_2, class:'form-check-input'
              = form.label @answer.question.choice_2, class:'form-check-label'
          - if @answer.question.choice_3 != ''
            div class='form-check mb-3'
              = form.check_box :choice_3, class:'form-check-input'
              = form.label @answer.question.choice_3, class:'form-check-label'
          - if @answer.question.choice_4 != ''
            div class='form-check mb-3'
              = form.check_box :choice_4, class:'form-check-input'
              = form.label @answer.question.choice_4, class:'form-check-label'
          - if @answer.question.choice_5 != ''
            div class='form-check mb-3'
              = form.check_box :choice_5, class:'form-check-input'
              = form.label @answer.question.choice_5, class:'form-check-label'
          - if @answer.question.choice_6 != ''
            div class='form-check mb-3'
              = form.check_box :choice_6, class:'form-check-input'
              = form.label @answer.question.choice_6, class:'form-check-label'
          nav
            ul class='pagination'
              - if @question.next != nil
                li.page-item
                  = form.submit 'Next', class:'page-link'
              - elsif @question.next == nil
                li.page-item
                  = form.submit 'Submit', class:'page-link' 
- else 
  div class='container d-flex align-items-center justify-content-center'
    div class='alert alert-primary'
      h4 class='alert heading' There are no questions yet
      p please come back latter when there are questions